# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken', models.BooleanField(default=False)),
                ('return_date', models.DateField(null=True)),
                ('archived_date', models.DateField(null=True)),
                ('archived', models.BooleanField(default=False)),
                ('ref_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('editor', models.CharField(blank=True, default='N/A', max_length=255, null=True)),
                ('publisher', models.CharField(blank=True, default='N/A', max_length=255, null=True)),
                ('published_year', models.CharField(blank=True, default='N/A', max_length=255, null=True)),
                ('isbn', models.CharField(blank=True, default='N/A', max_length=255, null=True)),
                ('cl_num', models.CharField(blank=True, default='N/A', max_length=255, null=True)),
                ('series', models.CharField(blank=True, default='N/A', max_length=255, null=True)),
                ('series_num', models.CharField(blank=True, default='N/A', max_length=255, null=True)),
                ('pages', models.CharField(blank=True, default='N/A', max_length=255, null=True)),
                ('height', models.CharField(blank=True, default='N/A', max_length=255, null=True)),
                ('image', models.TextField()),
                ('remarks', models.TextField(blank=True, default='No Remark Available', null=True)),
                ('summary', models.TextField(blank=True, default='No Summary Available', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.BookCategory')),
            ],
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='book_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.BookDetail'),
        ),
    ]
