# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='remarks',
            field=models.TextField(blank=True, default='No Remark Available', null=True),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='archived_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
