# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import members.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('nic', models.CharField(blank=True, default='N/A', max_length=255, null=True)),
                ('ref_id', models.CharField(default=members.models.random_ref, max_length=255, unique=True)),
                ('mobile', models.CharField(blank=True, default='N/A', max_length=255, null=True)),
                ('home', models.CharField(blank=True, default='N/A', max_length=255, null=True)),
                ('email', models.CharField(blank=True, default='N/A', max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, default='No Remark Available', null=True)),
                ('address', models.TextField(blank=True, default='No Address Available', null=True)),
                ('town', models.CharField(blank=True, default='N/A', max_length=255, null=True)),
                ('image', models.TextField()),
                ('web_active', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('password', models.TextField(default='')),
                ('ban_status', models.BooleanField(default=False)),
                ('registration_status', models.CharField(blank=True, default='Pending', max_length=255, null=True)),
                ('registration_expire', models.DateTimeField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='members',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.MemberTypes'),
        ),
    ]
