# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_members_archived_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='membertypes',
            name='fee',
            field=models.FloatField(default=True),
        ),
    ]
